---
- name: check handler behaviour with errrors
  hosts: localhost
  gather_facts: no
  force_handlers: yes
  tasks:
    - name: notify a handler
      debug:
        msg: hello
      changed_when: true
      notify: some handler

    - name: fail
      fail:

    - name: this never happens
      debug:
        msg: i am never executed :(

  handlers:
    - name: some handler
      debug:
        msg: running handler
